=== martijnportman/VPWorkshop/DefinitiesVoorbeelden/XSD/Books_v1.0.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:bks="http://www.dummy.org/booksXml" targetNamespace="http://www.dummy.org/booksXml" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="Books" type="bks:booksType"/>
	<!-- Complex Types -->
	<xsd:complexType name="booksType">
		<xsd:sequence>
			<xsd:element name="Book" type="bks:bookType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="bookType">
		<xsd:sequence>
			<xsd:element name="ISBN" type="bks:ISBN13SType"/>
			<xsd:element name="Writer" type="bks:writerType"/>
			<xsd:element name="Title" type="xsd:string"/>
			<xsd:element name="Genre" type="xsd:string"/>
			<xsd:element name="Price" type="bks:priceType"/>
			<xsd:element name="Publisher" type="bks:publisherType" maxOccurs="unbounded"/>
			<xsd:element name="PublishingDate" type="xsd:date"/>
			<xsd:element name="Review" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="bookId" type="xsd:string"/>
	</xsd:complexType>
	<xsd:complexType name="addressType">
		<xsd:sequence>
			<xsd:element name="POBoxNumber" type="xsd:string" minOccurs="0"/>
			<xsd:element name="BuildingHouseNumber" type="xsd:string" minOccurs="0"/>
			<xsd:element name="StreetName" type="xsd:string" minOccurs="0"/>
			<xsd:element name="CityName" type="xsd:string" minOccurs="0"/>
			<xsd:element name="StateProvince" type="xsd:string" minOccurs="0"/>
			<xsd:element name="PostalCode" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="priceType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:decimal">
				<xsd:attribute name="currency" type="bks:currencySType"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
	<xsd:complexType name="publisherType">
		<xsd:sequence>
			<xsd:element name="PublisherName" type="bks:alphaNumLength1to40SType"/>
			<xsd:element name="Address" type="bks:addressType"/>
			<xsd:element name="Regions" type="bks:regionsType" maxOccurs="5"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="regionsType">
		<xsd:sequence>
			<xsd:element name="Region" type="bks:regionSType" maxOccurs="5"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="writerType">
		<xsd:sequence>
			<xsd:element name="Author" type="xsd:string"/>
			<xsd:element name="Address" type="bks:addressType"/>
		</xsd:sequence>
	</xsd:complexType>
	<!-- Simple Types -->
	<xsd:simpleType name="alphaNumLength1to40SType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-zA-Z0-9]{1,40}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="currencySType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="pounds"/>
			<xsd:enumeration value="euros"/>
			<xsd:enumeration value="dollars"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="isbnSType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="\d{1}-\d{5}-\d{3}-\d{1}|\d{1}-\d{3}-\d{5}-\d{1}|\d{1}-\d{2}-\d{6}-\d{1}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="ISBN13SType">
		<xsd:restriction base="xsd:string">
			<xsd:length value="17"/>
			<xsd:pattern value="(978|979)-[0-9]{1,5}-[0-9]{1,7}-[0-9]{1,7}-[0-9]"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="regionSType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Africa"/>
			<xsd:enumeration value="America"/>
			<xsd:enumeration value="Antarctica"/>
			<xsd:enumeration value="Asia"/>
			<xsd:enumeration value="Europe"/>
			<xsd:enumeration value="Oceania"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== martijnportman/VPWorkshop/DefinitiesVoorbeelden/XSD/Books_v1.0.0_OK.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2008 sp1 (http://www.altova.com)-->
<bks:Books xsi:schemaLocation="http://www.dummy.org/booksXml Books_v1.0.0.xsd" xmlns:bks="http://www.dummy.org/booksXml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<bks:Book bookId="001">
		<bks:ISBN>978-1-2345-6789-0</bks:ISBN>
		<bks:Writer>
			<bks:Author>John Doe</bks:Author>
			<bks:Address>
				<bks:BuildingHouseNumber>123</bks:BuildingHouseNumber>
				<bks:StreetName>StreetName1</bks:StreetName>
				<bks:CityName>CityName1</bks:CityName>
				<bks:StateProvince>StateProvince1</bks:StateProvince>
				<bks:PostalCode>12345</bks:PostalCode>
			</bks:Address>
		</bks:Writer>
		<bks:Title>My interesting life</bks:Title>
		<bks:Genre>Biography</bks:Genre>
		<bks:Price currency="euros">9.99</bks:Price>
		<bks:Publisher>
			<bks:PublisherName>PublishersName11</bks:PublisherName>
			<bks:Address>
				<bks:POBoxNumber>12345</bks:POBoxNumber>
				<bks:BuildingHouseNumber>231</bks:BuildingHouseNumber>
				<bks:StreetName>StreetName11</bks:StreetName>
				<bks:CityName>CityName11</bks:CityName>
				<bks:StateProvince>StateProvince11</bks:StateProvince>
				<bks:PostalCode>11345</bks:PostalCode>
			</bks:Address>
			<bks:Regions>
				<bks:Region>Africa</bks:Region>
				<bks:Region>Europe</bks:Region>
			</bks:Regions>
		</bks:Publisher>
		<bks:Publisher>
			<bks:PublisherName>PublishersName12</bks:PublisherName>
			<bks:Address>
				<bks:POBoxNumber>23451</bks:POBoxNumber>
				<bks:BuildingHouseNumber>312</bks:BuildingHouseNumber>
				<bks:StreetName>StreetName12</bks:StreetName>
				<bks:CityName>CityName12</bks:CityName>
				<bks:StateProvince>StateProvince12</bks:StateProvince>
				<bks:PostalCode>12345</bks:PostalCode>
			</bks:Address>
			<bks:Regions>
				<bks:Region>Asia</bks:Region>
			</bks:Regions>
		</bks:Publisher>
		<bks:PublishingDate>2019-01-01</bks:PublishingDate>
		<bks:Review>Very, very good</bks:Review>
	</bks:Book>
	<bks:Book bookId="002">
		<bks:ISBN>978-2-3456-7890-1</bks:ISBN>
		<bks:Writer>
			<bks:Author>Jane Whats Her Name</bks:Author>
			<bks:Address>
				<bks:BuildingHouseNumber>456</bks:BuildingHouseNumber>
				<bks:StreetName>StreetName2</bks:StreetName>
				<bks:CityName>CityName2</bks:CityName>
				<bks:StateProvince>StateProvince2</bks:StateProvince>
				<bks:PostalCode>23456</bks:PostalCode>
			</bks:Address>
		</bks:Writer>
		<bks:Title>My favorite destinations</bks:Title>
		<bks:Genre>Travel</bks:Genre>
		<bks:Price currency="euros">19.99</bks:Price>
		<bks:Publisher>
			<bks:PublisherName>PublishersName21</bks:PublisherName>
			<bks:Address>
				<bks:POBoxNumber>23451</bks:POBoxNumber>
				<bks:BuildingHouseNumber>456</bks:BuildingHouseNumber>
				<bks:StreetName>StreetName21</bks:StreetName>
				<bks:CityName>CityName21</bks:CityName>
				<bks:StateProvince>StateProvince21</bks:StateProvince>
				<bks:PostalCode>22345</bks:PostalCode>
			</bks:Address>
			<bks:Regions>
				<bks:Region>America</bks:Region>
				<bks:Region>Europe</bks:Region>
			</bks:Regions>
		</bks:Publisher>
		<bks:Publisher>
			<bks:PublisherName>PublishersName12</bks:PublisherName>
			<bks:Address>
				<bks:POBoxNumber>23451</bks:POBoxNumber>
				<bks:BuildingHouseNumber>312</bks:BuildingHouseNumber>
				<bks:StreetName>StreetName12</bks:StreetName>
				<bks:CityName>CityName12</bks:CityName>
				<bks:StateProvince>StateProvince12</bks:StateProvince>
				<bks:PostalCode>12345</bks:PostalCode>
			</bks:Address>
			<bks:Regions>
				<bks:Region>Asia</bks:Region>
			</bks:Regions>
		</bks:Publisher>
		<bks:PublishingDate>2019-02-02</bks:PublishingDate>
		<bks:Review>Very, very interesting</bks:Review>
	</bks:Book>
</bks:Books>
